Set a small delay to prevent rapid submissions on Enter
wpai-inc/agentwp pull request #198
Opened 2024-10-08 14:45 UTC by sergikhizanishvili

2024-10-08 15:06 UTC, greghunt requested changes
Can we not disable sending if submitting, instead of using delays?

2024-10-08 15:43 UTC, sergikhizanishvili commented
> Can we not disable sending if submitting, instead of using delays?

Will do.

2024-10-09 07:19 UTC, sergikhizanishvili commented
@greghunt Changed according to your comment

2024-10-09 08:12 UTC, greghunt approved these changes

2024-10-09 08:12 UTC, merged